diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.DiaryList.as_view(), name='list'),
    path('detail/<int:pk>/', views.DiaryDetail.as_view(), name='detail'),
    path('delete/<int:diary_id>/', views.DiaryDelete, name='delete'),
    path('add/', views.DiaryAdd, name='add-note'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('diary/', include('diary.urls')),
    path('admin/', admin.site.urls),
]

diary/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """日記のカテゴリ"""
    name = models.CharField('タイトル', max_length=255)

    def __str__(self):
        return self.name
    
class DiaryQuerySet(models.QuerySet):

    def published(self):
        return self.filter(created_at__lte=timezone.now())
    
class Diary(models.Model):
    """日記"""
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    objects = DiaryQuerySet.as_manager()

    def __str__(self):
        return self.title
    

diary/forms.py
from django import forms
from .models import Diary


class DiarySearchForm(forms.Form):
    """検索フォーム。"""
    key_word = forms.CharField(
        label='検索キーワード',
        required=False,
    )

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'text', 'category')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {'placeholder': 'Title', 'class': 'input-title'}
        self.fields['text'].widget.attrs = {'placeholder': 'Text',  'class': 'input-text'}
        self.fields['category'].widget.attrs = {'placeholder': 'Category',  'class': 'input-category'}

diary/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect

from .forms import DiaryCreateForm

from .models import Diary, Category


class ArchiveListMixin:
    model = Diary
    paginate_by = 12
    date_field = 'created_at'
    template_name = 'diary/diary_list.html'
    allow_empty = True
    make_object_list = True

    
class DiaryListMixin(generic.base.ContextMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['diary_list'] = Diary.objects.all().order_by('created_at').reverse()
        return context
    
    
class DiaryList(DiaryListMixin, ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '最近の日記'
        return context

    
class DiaryDetail(DiaryListMixin, generic.UpdateView):
    template_name = 'diary/diary_detail.html'
    model = Diary
    success_url = reverse_lazy('diary:list')
    form_class = DiaryCreateForm


def DiaryDelete(request, diary_id):
    diary_pk = get_object_or_404(Diary, pk=diary_id)
    diary_pk.delete()
    return redirect('diary:list')


def DiaryAdd(request):
    category = Category.objects.get(pk=1)
    Diary.objects.create(title='新規作成', category=category)
    return redirect('diary:list')
   

diary/templates/diary/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block meta_title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'diary/style.css' %}">
    <script src="{% static 'diary/diary.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:300,400&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/fe12d9791d.js" crossorigin="anonymous"></script>
    {% block extrahead %}{% endblock %}
</head>

<body>

<!-- ヘッダー -->
<header>
    <a href="{% url 'diary:list' %}">
        <p id="title">Note</p>
    </a>
</header>

<main>
    <!-- サイドメニュー -->
    <div class="side">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'diary:add-note' %}" class="nav-link">
                    <i class="fa-solid fa-circle-plus fa-3x"></i>
                </a>
            </li>
        </ul>
    </div>

    <!-- メインコンテンツ -->
    {% block content %}{% endblock %}
        
</main>

</body>
</html>

diary/templates/diary/diary_detail.html
{% extends 'diary/base.html' %}

{% block meta_title %}{{ diary.title }} - {{ block.super }}{% endblock %}

{% block content %}
<div id="diary-list" class="note-list flex-column">

    {% for diary in diary_list %}

        <article class="diary">
            <a href="{% url 'diary:detail' diary.pk %}" id="diary-link">
                <h2 class="diary-title">{{ diary.title }}</h2>
                <p class="meta">
                    <time datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y年n月j日' }}</time>
                    -
                    {{ diary.category }}
                </p>
                <div class="contents">
                    <p>
                        {{ diary.text | truncatechars:100 }}
                    </p>
                </div>
            </a>
        </article>


    {% empty %}
        <p>記事が見つかりませんでした。</p>
    {% endfor %}

</div>
<div class="note-wrap">
    <form method="post">
        {% csrf_token %}
        <div class="setting-container">
            <a href="{% url 'diary:delete' diary.pk %}" class="diary-delete-button" onclick='return confirm("本当に削除しますか？");'>
                <i class="fa-solid fa-trash-can fa-lg"></i>
            </a>
            <div class = "btn-form">
                <button type="submit" class="btn btn-success">保存</button>
            </div>
        </div>
        <div class="edit-container">
            <div class="form-title">{{ form.title }}</div>
            <div class="form-category">{{ form.category }}</div>
            <div class="form-textarea">{{ form.text }}</div>
        </div>
    </form>
</div>
{% endblock %}

diary/templates/diary/diary_list.html
{% extends 'diary/base.html' %}

{% block meta_title %}{{ diary.title }} Noteリスト {{ block.super }}{% endblock %}

{% block content %}
<div id="diary-list" class="note-list flex-column">

    {% for diary in diary_list %}

        <article class="diary">
            <a href="{% url 'diary:detail' diary.pk %}" id="diary-link">
                <h2 class="diary-title">{{ diary.title }}</h2>
                <p class="meta">
                    <time datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y年n月j日' }}</time>
                    -
                    {{ diary.category }}
                </p>
                <div class="contents">
                    <p>
                        {{ diary.text | truncatechars:100 }}
                    </p>
                </div>
            </a>
        </article>


    {% empty %}
        <p>記事が見つかりませんでした。</p>
    {% endfor %}

</div>
<div class="note-wrap">
    <div class="note-list-comment">noteを指定してください。</div>
</div>
{% endblock %}

diary/templates/diary/includes/search_form.html
<form action="{% url 'diary:search' %}" method="GET">
    <div class="field">
        {{ search_form.key_word }}
        <button type="submit" id="search" class="search-btn"></button>
    </div>
</form>